name: Agda-Unimath CI
on:
  # To run this workflow manually
  workflow_dispatch:
    inputs:
      ref:
        description: the repository ref to build
        required: true
        default: main

  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

# Cancel previous runs of the same branch
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.run_id }}'
  cancel-in-progress: true

env:
  AGDAHTMLFLAGS: --only-scope-checking --html --html-highlight=code --html-dir=docs --css=docs/Agda.css

jobs:
  check-ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macOS-latest , ubuntu-latest ]
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Install Agda
        uses: wenkokke/setup-agda@v2.0.0
        with:
          agda-version: '2.6.3'

      - name: Typecheck the whole formalisation
        run: |
          cd main
          make check

      - name: Generate HTML
        if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        id: gen-html
        run: |
          cd main
          make agda-html

      - uses: r-lib/actions/setup-pandoc@v2
        if: ${{ sucess() }}
        with:
          pandoc-version: 2.19.2

      - name: Deploy HTML to github pages
        if: steps.gen-html.outputs.exit_status == 0
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: main/docs
          enable_jekyll: true
